using System.Collections.Generic;
using CrushRoyale.Core.Board;

namespace CrushRoyale.Core.Story
{
    /// <summary>The 5 kingdoms of Crystalheim, one per act.</summary>
    public enum Kingdom : byte
    {
        North = 0,
        East = 1,
        West = 2,
        South = 3,
        Central = 4
    }

    public enum ObjectiveType : byte
    {
        ReachScore = 0,
        ClearIce = 1,
        CollectColor = 2,
        BreakStones = 3,
        DefeatBoss = 4
    }

    /// <summary>Difficulty label shown on the map: a sawtooth of easy stages, a hard one, now and then a super hard one.</summary>
    public enum StageTier : byte
    {
        Normal = 0,
        Hard = 1,
        SuperHard = 2
    }

    public enum BossKind : byte
    {
        None = 0,
        MiniBoss = 1,
        ChapterBoss = 2,
        ActBoss = 3,
        FinalBoss = 4
    }

    /// <summary>One win condition. Stages can combine several (all must be completed).</summary>
    public sealed class StageObjective
    {
        public ObjectiveType Type { get; set; }

        /// <summary>Score / layers / gems / stones / boss HP. For ClearIce, 0 means "all ice on the board".</summary>
        public int Target { get; set; }

        /// <summary>Only for CollectColor.</summary>
        public PieceColor Color { get; set; } = PieceColor.None;

        public override string ToString() => Type == ObjectiveType.CollectColor ? Type + " " + Target + " " + Color : Type + " " + Target;
    }

    /// <summary>
    /// Static description of a story stage (Task 8). Generated by StageCatalog and exported to JSON;
    /// identical for every player (fixed seed) so stage replays and leaderboards are comparable.
    /// </summary>
    public sealed class StageData
    {
        public int Id { get; set; }

        public int Act { get; set; }

        /// <summary>Chapter number across the whole campaign (1-50).</summary>
        public int Chapter { get; set; }

        /// <summary>1-based position inside its chapter.</summary>
        public int IndexInChapter { get; set; }

        public Kingdom Kingdom { get; set; }

        public BossKind BossKind { get; set; }

        public bool IsBoss => BossKind != BossKind.None;

        public string BossId { get; set; }

        /// <summary>
        /// Timed stage: unlimited moves, beat the goal before the clock runs out. Otherwise a moves stage: limited moves and
        /// no visible clock (<see cref="TimeLimitMs"/> is then only a generous safety cap).
        /// </summary>
        public bool Timed { get; set; }

        public StageTier Tier { get; set; }

        public int TimeLimitMs { get; set; }

        /// <summary>0 on timed stages (unlimited moves).</summary>
        public int MoveLimit { get; set; }

        public int TargetScore { get; set; }

        public int TwoStarScore { get; set; }

        public int ThreeStarScore { get; set; }

        /// <summary>0-1000. GDD: stage 500 = 50%, stage 1000 = 100%.</summary>
        public int DifficultyPermille { get; set; }

        public float DifficultyPercent => DifficultyPermille / 10f;

        public int ColorCount { get; set; } = 6;

        public int StoneCount { get; set; }

        public int StoneHp { get; set; } = 1;

        public int IceCells { get; set; }

        public int IceLayers { get; set; } = 1;

        public List<StageObjective> Objectives { get; set; } = new List<StageObjective>();

        public int BossHp { get; set; }

        public int BossPhases { get; set; }

        public int BossStonesPerPhase { get; set; }

        /// <summary>Companion featured on the stage (portrait in dialogues / world map).</summary>
        public string CharacterId { get; set; }

        public string DialogueBeforeId { get; set; }

        public string DialogueAfterId { get; set; }

        public bool HasCinematic { get; set; }

        public int RewardCoins { get; set; }

        public int RewardOrbes { get; set; }

        public ulong Seed { get; set; }

        /// <summary>True for post-campaign endless stages (1001+).</summary>
        public bool IsEndless { get; set; }
    }
}
