using System.Collections.Generic;
using CrushRoyale.Core.Board;
using CrushRoyale.Core.Config;
using CrushRoyale.Core.Story;
using UnityEngine;

namespace CrushRoyale.Game.UI
{
    /// <summary>
    /// Illustrated art from Assets/Resources/Art (generated by tools/art/process_art.py). Every getter returns null when
    /// the file is missing so callers keep the procedural fallback and the game stays playable without assets.
    /// </summary>
    public static class ArtLibrary
    {
        private static readonly Dictionary<string, Sprite> Cache = new Dictionary<string, Sprite>();

        /// <summary>Equipped gem skin folder used by the board ("runes", "jewels", "season"), null for the classic gems.</summary>
        public static string GemSkin { get; set; }

        public static Sprite Gem(PieceColor color) => Gem(color, GemSkin);

        /// <summary>Gem art of a skin folder, falling back to the classic gem when that skin has no art.</summary>
        public static Sprite Gem(PieceColor color, string skinFolder)
        {
            string file = color.ToString().ToLowerInvariant();
            Sprite skinned = string.IsNullOrEmpty(skinFolder) ? null : Load("Art/Gems/" + skinFolder + "/" + file);
            return skinned ?? Load("Art/Gems/" + file);
        }

        /// <summary>Art folder of a piece skin cosmetic id.</summary>
        public static string GemSkinFolder(string pieceSkinId)
        {
            if (string.IsNullOrEmpty(pieceSkinId))
            {
                return null;
            }
            if (pieceSkinId == "pieces.runes")
            {
                return "runes";
            }
            if (pieceSkinId == "pieces.gems")
            {
                return "jewels";
            }
            return pieceSkinId.StartsWith("bp.s", System.StringComparison.Ordinal) ? "season" : null;
        }

        public static Sprite Stone() => Load("Art/Gems/stone");

        public static Sprite Ice() => Load("Art/Gems/ice");

        /// <summary>Iron bands laid over a stone that still needs two hits.</summary>
        public static Sprite StoneBands() => Load("Art/Gems/stone_bands");

        /// <summary>3D overlay of a bonus gem: double-arrow rod (lines) or spiked gold ring (area bomb).</summary>
        public static Sprite Special(PieceType type)
        {
            switch (type)
            {
                case PieceType.LineHorizontal: return Load("Art/Gems/special_line_h");
                case PieceType.LineVertical: return Load("Art/Gems/special_line_v");
                case PieceType.AreaBomb: return Load("Art/Gems/special_bomb");
                default: return null;
            }
        }

        // Same order as PowerUpType.
        private static readonly string[] PowerUpFiles =
        {
            "time_bomb", "coin_boost", "starburst", "multiplier", "chain", "potion", "bomb", "tornado", "infinity"
        };

        public static Sprite PowerUp(PowerUpType type)
        {
            int index = (int)type;
            return index < PowerUpFiles.Length ? Load("Art/PowerUps/" + PowerUpFiles[index]) : null;
        }

        public static Sprite Logo() => Load("Art/logo");

        /// <summary>UI icon: coin, orb, heart, trophy, star, crown, lock, chest, guild.</summary>
        public static Sprite Icon(string name) => Load("Art/Icons/" + name);

        /// <summary>Boss illustration: one per act boss, Valdorax for the finale, the crystal golem for minor bosses.</summary>
        public static Sprite Boss(StageData stage)
        {
            if (stage == null || !stage.IsBoss)
            {
                return null;
            }
            if ((stage.BossId ?? string.Empty).Contains("valdorax"))
            {
                return Load("Art/Bosses/valdorax");
            }
            if (stage.BossKind != BossKind.ActBoss)
            {
                return GuildBoss();
            }
            switch (stage.Kingdom)
            {
                case Kingdom.North: return Load("Art/Bosses/frostbane");
                case Kingdom.East: return Load("Art/Bosses/eclipse_pharaoh");
                case Kingdom.West: return Load("Art/Bosses/treant");
                case Kingdom.South: return Load("Art/Bosses/pyraxis");
                default: return Load("Art/Bosses/valdorax");
            }
        }

        public static Sprite GuildBoss() => Load("Art/Bosses/golem");

        /// <summary>Weekly guild boss portrait: the six illustrated bosses take turns (index 1 = the crystal golem).</summary>
        public static Sprite GuildBoss(int index)
        {
            string[] bosses = { "golem", "treant", "frostbane", "pyraxis", "eclipse_pharaoh", "valdorax" };
            return Load("Art/Bosses/" + bosses[(System.Math.Max(1, index) - 1) % bosses.Length]) ?? GuildBoss();
        }

        /// <summary>Dialogue portrait by story character id ("hero", "lyra", ...).</summary>
        public static Sprite Character(string id) => string.IsNullOrEmpty(id) ? null : Load("Art/Characters/" + id);

        public static Sprite Background(Kingdom kingdom)
        {
            switch (kingdom)
            {
                case Kingdom.North: return Load("Art/Backgrounds/frostreach");
                case Kingdom.East: return Load("Art/Backgrounds/sunspire");
                case Kingdom.West: return Load("Art/Backgrounds/verdant");
                case Kingdom.South: return Load("Art/Backgrounds/emberfall");
                default: return Load("Art/Backgrounds/crystalheim");
            }
        }

        public static Sprite Load(string path)
        {
            if (Cache.TryGetValue(path, out Sprite cached))
            {
                return cached;
            }

            Sprite sprite = Resources.Load<Sprite>(path);
            if (sprite == null)
            {
                Texture2D texture = Resources.Load<Texture2D>(path);
                if (texture != null)
                {
                    sprite = Sprite.Create(texture, new Rect(0, 0, texture.width, texture.height), new Vector2(0.5f, 0.5f), 100f);
                }
            }
            Cache[path] = sprite;
            return sprite;
        }
    }
}
