<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CrushRoyale.Core\CrushRoyale.Core.csproj" />
    <ProjectReference Include="..\CrushRoyale.Contracts\CrushRoyale.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.AndroidPublisher.v3" Version="1.76.0.4261" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
